spring:
  cloud:
    gateway:
      routes:
        - id: backPatient-route
          uri: http://backpatient:8082
          predicates:
            - Path=/patients/**
        - id: backNotes-route
          uri: http://backnotes:8083
          predicates:
            - Path=/notes/**
        - id: backDiabete-route
          uri: http://backdiabete:8084
          predicates:
            - Path=/diabetes/**